Feature/24 highlihting code after launching
alexchmykhalo/kuzya pull request #34
Opened 2017-02-17 12:55 UTC by BaranovMykola

This branch has been created from feature/22-temporary-file (it still need code review), because this feature  are relative to #22.

2017-03-08 11:59 UTC, alexchmykhalo requested changes

2017-03-08 11:59 UTC, alexchmykhalo commented on src/kuzya.cpp
> +    tFile = new QTemporaryFile;
Please, choose better name for member + use m prefix for members.

2017-03-08 11:59 UTC, alexchmykhalo commented on src/kuzya.cpp
> +    if(settings->getIsFileReopenEnabled())
it better to use either "get" or "is" prefix for getters (I mean name it: getFileReopenState() or isFileReopenEnabled()). I suggest to use second one (isFileReopenEnabled()) - it is more in Qt fashion.

2017-03-08 11:59 UTC, alexchmykhalo commented on src/kuzya.cpp
> +    QString tfname = tFile->fileName();
Please, find better names for this variables..

2017-03-08 11:59 UTC, alexchmykhalo commented on src/kuzya.cpp
> +    QSettings* settings = new QSettings(QApplication::applicationDirPath()+"/settings.ini", QSettings::IniFormat);
We already have settings in OptionsDialog class. Could we use that one?

2017-03-09 20:39 UTC, BaranovMykola commented on src/kuzya.cpp
> +    QSettings* settings = new QSettings(QApplication::applicationDirPath()+"/settings.ini", QSettings::IniFormat);
I would like to use the same ini file. But according to your last comment i am not allowed to use OptionDialog class. So, i tried to work with this file without OptionDialog class. Am i wrong?

> We should stick to single responsibility principle (see SOLID for reference). Class called OptionsDialog - that means that it is dialog that contains UI for Kuzya options. That is its only responsibility. It should not take care of loading temporary files, dealing with main window configuration, etc. This class should serve only one purpose - manage UI for setting Kuzya options.

2017-04-10 15:38 UTC, BaranovMykola commented
Extra instance of QSettings* in kuzya.cpp was removed. Used OptionsDialog's getter instead

2018-04-04 23:29 UTC, merged