Create About Kuzya *.ui, *.cpp and *.hpp
alexchmykhalo/kuzya pull request #36
Opened 2017-02-17 15:50 UTC by grafit7

Created UI for About Kuzya, and code which contained in slotAbout() moved to *.hpp and *.cpp

2017-03-05 12:56 UTC, alexchmykhalo commented on src/kuzya.cpp
> +#include "kuzyaabout.hpp"
Why it has extension .hpp?

2017-03-05 12:56 UTC, alexchmykhalo commented on src/kuzya.cpp
> +#include "kuzyaabout.hpp"
I'll also suggest to find better name for class and files (aboutdialog.*, aboutkuzya.*) -it sounds a bit more natural.

2017-03-05 12:56 UTC, alexchmykhalo commented on src/kuzya.cpp
> +    kuzya.readAuthors();
It is ok to have all this methods to separate diffetent operations that dialog performs. But I see no point to make them public and call them here. What if someone will not know in that order to call all that methods? What if someone forgot to call one of them?

I sugest make them private and call in constructor.

2017-03-05 12:56 UTC, alexchmykhalo commented on src/kuzya.cpp
> +    kuzya.readAuthors();
Another thing that I see - that KuzyaAbout dialog has a number of dependencies. Kuzya version and build date are used from "version.h", also path to AUTHORS file is hardcoded. 

I suggest to make setter methods that will take version, build date and path to file with authors information. Then KuzyaAbout dialog will be more independent class that will be responsible only for displaying information about Kuzua IDE and will not know all application related details (such as AUTHORS file location, how version and build date are presented and where stored)

2017-03-05 12:56 UTC, alexchmykhalo commented on src/kuzya.cpp
> +    kuzya.readAuthors();
It is event better to pass Kuzya version,  build date and  path to AUTHORS file - as a constructor parameters. KuzyaAbout dialog will not show correct information if we not set all that, right?

2017-03-05 12:56 UTC, alexchmykhalo commented on src/kuzyaabout.hpp
> +  const QString *fileName = new QString(":/AUTHORS.txt");
Please, use m prefix for member names.

2017-03-05 12:56 UTC, alexchmykhalo commented on src/kuzyaabout.cpp
> +void KuzyaAbout::fillWindow()
I think you can make all this in Designer.

2017-03-05 21:22 UTC, grafit7 commented on src/kuzya.cpp
> +    kuzya.readAuthors();
you're right!

2017-03-08 11:08 UTC, alexchmykhalo commented on src/aboutkuzya.cpp
> +  exec();
Never do exec() or other such things from the constructor. Developer should have an opportunity to open dialog when it is needed. That is why exec() is a separate method.

Please, move that call to place where instance is created.

2017-03-08 11:08 UTC, alexchmykhalo commented on src/aboutkuzya.cpp
> +      qCritical()<< "File doesn't exist"<<*mFileName<<endl;
You could return from method if file does not exist - it will not open anyway.

2017-03-08 11:08 UTC, alexchmykhalo commented on src/aboutkuzya.cpp
> +AboutKuzya::AboutKuzya(QWidget *parent, QVersionNumber *verKuzia, QDate *buildDate, QString *fileName) :
You need to place "QWidget *parent" argument in the end of argument list. Then you could make it default (=nullptr).

2017-03-08 11:08 UTC, alexchmykhalo commented on src/aboutkuzya.h
> +  explicit AboutKuzya(QWidget *parent = 0, QVersionNumber *verKuzia = 0, QDate *buildDate = 0, QString *fileName = 0);
Why you need to pass all this arguments by pointer?

2017-03-08 11:30 UTC, alexchmykhalo reviewed
Please, see new review comments.

2017-03-12 12:29 UTC, grafit7 commented
Check it out

2017-03-12 20:25 UTC, alexchmykhalo requested changes
Please, see review comments.

2017-03-12 20:25 UTC, alexchmykhalo commented on src/aboutkuzya.cpp
> +  mIn = new QTextStream(mFile);
Read authors will be called regardless of checkFile() call state. I suggest to merge this two nethods to one. In that new method you could check for authors file and skip reading if it is not exist.

2017-03-12 20:25 UTC, alexchmykhalo commented on src/aboutkuzya.cpp
> +  mTextInf = new QString;
Why you need to create QString, QTextStream and QFile on a heap? Please, use stack as much as possible.

2017-03-12 20:25 UTC, alexchmykhalo commented on src/aboutkuzya.h
> +  QFile *mFile;
Again, you do not need all this pointers. You could create string, stream and file objects locally in your method.

2017-07-13 12:23 UTC, alexchmykhalo approved these changes

2017-07-13 12:38 UTC, merged